/**
 * Canonical wave spawn scheduling.
 *
 * Waves are generated by buildWave(n, map.waveMods) — not a static per-map catalog.
 * Spawn cadence (TarkovTD startWave):
 *   start delay 400ms
 *   each group: count enemies, +gap ms between them
 *   +700ms padding after every group
 * Lane assignment: assignSpawnLane(spawnIndex, laneCount) round-robin. Groups have no per-entry lane.
 */

import { waveScale, type WaveGroup } from "./data";
import { assignSpawnLane } from "./lanes";
import type { EnemyKind } from "./types";

export const WAVE_START_DELAY_MS = 400;
export const WAVE_GROUP_PADDING_MS = 700;

export type WaveSpawnEvent = {
  at: number;
  kind: EnemyKind;
  lane: number;
};

export function scheduleWave(
  groups: readonly WaveGroup[],
  laneCount: number,
  startDelayMs = WAVE_START_DELAY_MS,
  groupPaddingMs = WAVE_GROUP_PADDING_MS,
): WaveSpawnEvent[] {
  const lanes = Math.max(1, laneCount);
  const q: WaveSpawnEvent[] = [];
  let at = startDelayMs;
  let spawnIndex = 0;
  for (const g of groups) {
    const count = Math.max(0, Math.round(g.count));
    for (let i = 0; i < count; i++) {
      q.push({ at, kind: g.kind, lane: assignSpawnLane(spawnIndex, lanes) });
      spawnIndex += 1;
      at += Math.max(0, g.gap);
    }
    at += groupPaddingMs;
  }
  return q;
}

/** Time from wave start until the last enemy is queued to spawn. 0 if empty. */
export function spawnDurationMs(groups: readonly WaveGroup[]): number {
  const events = scheduleWave(groups, 1);
  if (events.length === 0) return 0;
  return events[events.length - 1]!.at;
}

export function totalEnemyCount(groups: readonly WaveGroup[]): number {
  return groups.reduce((a, g) => a + Math.max(0, Math.round(g.count)), 0);
}

export function compositionShares(groups: readonly WaveGroup[]): { kind: EnemyKind; count: number; share: number }[] {
  const counts = new Map<EnemyKind, number>();
  let total = 0;
  for (const g of groups) {
    const n = Math.max(0, Math.round(g.count));
    if (n <= 0) continue;
    counts.set(g.kind, (counts.get(g.kind) ?? 0) + n);
    total += n;
  }
  const kinds = [...counts.keys()];
  return kinds.map((kind) => ({
    kind,
    count: counts.get(kind)!,
    share: total > 0 ? counts.get(kind)! / total : 0,
  }));
}

export function cloneWaveGroups(groups: readonly WaveGroup[]): WaveGroup[] {
  return groups.map((g) => ({ kind: g.kind, count: g.count, gap: g.gap }));
}

/** HP snapshot at spawn. Live instances keep this maxHp; later HP overrides do not heal. */
export function spawnedEnemyHp(baseHp: number, wave: number, mapHpMult: number, enemyHpMod = 1): number {
  return Math.round(baseHp * waveScale(wave).hp * mapHpMult * enemyHpMod);
}
