import type { MapDef } from "../map";

/** Locked PINE CUT export applied literally. */
export const WOODS_MAP: MapDef = {
  id: "woods",
  name: "PINE CUT",
  threat: 1,
  threatLabel: "LOW THREAT",
  desc: "Long winding trail through the pines. Slow scav pressure, lots of room to set up.",
  hpMult: 0.85,
  lootMult: 0.85,
  waveMods: { countMult: 0.6, heavyDelay: 3 },
  /** QA-baked Pine Cut compositions (Wave Lab patch). */
  authoredWaves: {
    1: {
      name: "SCAV ROAMERS",
      groups: [
        { kind: "scav", count: 4, gap: 600 },
        { kind: "sniperScav", count: 1, gap: 500 },
      ],
    },
    2: {
      name: "SCAV ROAMERS",
      groups: [{ kind: "scav", count: 6, gap: 600 }],
    },
    3: {
      name: "CHECKPOINT PROBE",
      groups: [
        { kind: "scav", count: 5, gap: 475 },
        { kind: "sniperScav", count: 2, gap: 500 },
      ],
    },
    4: {
      name: "CHECKPOINT PROBE",
      groups: [
        { kind: "scav", count: 5, gap: 535 },
        { kind: "sniperScav", count: 3, gap: 500 },
      ],
    },
    5: {
      name: "SHOTGUN SWEEP",
      groups: [
        { kind: "scav", count: 2, gap: 510 },
        { kind: "sniperScav", count: 5, gap: 520 },
      ],
    },
    6: {
      name: "SHOTGUN SWEEP",
      groups: [
        { kind: "scav", count: 5, gap: 488 },
        { kind: "sniperScav", count: 6, gap: 520 },
      ],
    },
    7: {
      name: "RIFLE LINE",
      groups: [
        { kind: "scav", count: 5, gap: 466 },
        { kind: "sniperScav", count: 2, gap: 520 },
        { kind: "raider", count: 2, gap: 640 },
      ],
    },
    8: {
      name: "RIFLE LINE",
      groups: [
        { kind: "scav", count: 7, gap: 444 },
        { kind: "sniperScav", count: 3, gap: 520 },
        { kind: "raider", count: 3, gap: 640 },
      ],
    },
    9: {
      name: "ARMORED PUSH",
      groups: [
        { kind: "scav", count: 4, gap: 422 },
        { kind: "sniperScav", count: 4, gap: 520 },
        { kind: "raider", count: 4, gap: 640 },
      ],
    },
    10: {
      name: "RAID BOSS — ENFORCER",
      groups: [
        { kind: "boss", count: 1, gap: 1600 },
        { kind: "raider", count: 4, gap: 500 },
      ],
    },
  },
  geo: { x: 22, y: 30 },
  sector: "SECTOR N-2",
  palette: {
    grassA: "#2e3a24",
    grassB: "#27321f",
    grassC: "#222c1b",
    speckLight: "#3a4a2a",
    speckDark: "#1b2415",
    roadOuter: "#3a3328",
    roadMid: "#4a4034",
    roadInner: "#5b503f",
    roadLine: "#6d6250",
  },
  path: [[1, 13], [1, 12], [1, 11], [1, 10], [2, 10], [2, 9], [2, 8], [1, 8], [1, 7], [1, 6], [1, 5], [1, 4], [1, 3], [2, 3], [3, 3], [3, 4], [3, 5], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [7, 5], [7, 4], [8, 4], [9, 4], [10, 4], [11, 4], [11, 5], [11, 6], [11, 7], [12, 7], [13, 7], [14, 7], [15, 7], [15, 6], [15, 5], [15, 4], [15, 3], [16, 3], [17, 3], [17, 2], [17, 1], [17, 0], [17, -1]],
  props: [
    { tx: 0, ty: 0, type: "tree" as const },
    { tx: 1, ty: 0, type: "tree" as const },
    { tx: 2, ty: 0, type: "rock" as const },
    { tx: 3, ty: 0, type: "tree" as const },
    { tx: 15, ty: 0, type: "tree" as const },
    { tx: 19, ty: 0, type: "tree" as const },
    { tx: 0, ty: 1, type: "tree" as const },
    { tx: 5, ty: 1, type: "tree" as const },
    { tx: 18, ty: 2, type: "tree" as const },
    { tx: 13, ty: 3, type: "tree" as const },
    { tx: 2, ty: 4, type: "rock" as const },
    { tx: 19, ty: 4, type: "tree" as const },
    { tx: 2, ty: 5, type: "tree" as const },
    { tx: 6, ty: 5, type: "rock" as const },
    { tx: 10, ty: 5, type: "tree" as const },
    { tx: 17, ty: 5, type: "tree" as const },
    { tx: 18, ty: 5, type: "tree" as const },
    { tx: 19, ty: 5, type: "tree" as const },
    { tx: 18, ty: 6, type: "tree" as const },
    { tx: 19, ty: 6, type: "tree" as const },
    { tx: 4, ty: 7, type: "tree" as const },
    { tx: 5, ty: 7, type: "tree" as const },
    { tx: 7, ty: 8, type: "tree" as const },
    { tx: 12, ty: 8, type: "tree" as const },
    { tx: 17, ty: 8, type: "tree" as const },
    { tx: 19, ty: 8, type: "tree" as const },
    { tx: 10, ty: 9, type: "tree" as const },
    { tx: 18, ty: 9, type: "tree" as const },
    { tx: 19, ty: 9, type: "tree" as const },
    { tx: 0, ty: 10, type: "rock" as const },
    { tx: 6, ty: 10, type: "tree" as const },
    { tx: 19, ty: 10, type: "tree" as const },
    { tx: 0, ty: 11, type: "tree" as const },
    { tx: 0, ty: 12, type: "tree" as const },
    { tx: 2, ty: 12, type: "tree" as const },
    { tx: 4, ty: 12, type: "tree" as const },
    { tx: 19, ty: 12, type: "tree" as const },
  ],
  checkpoint: [],
  cover: [],
  crates: [[19, 7], [19, 11], [3, 12]],
  mountain: [[4, 0], [5, 0], [6, 0], [7, 0], [8, 0], [9, 0], [10, 0], [11, 0], [12, 0], [13, 0], [14, 0], [6, 1], [7, 1], [8, 1], [9, 1], [10, 1], [11, 1], [12, 1], [8, 2], [9, 2], [10, 2], [7, 10], [8, 10], [9, 10], [10, 10], [11, 10], [12, 10], [7, 11], [8, 11], [9, 11], [10, 11], [11, 11], [12, 11], [13, 11], [14, 11], [15, 11], [16, 11], [17, 11], [6, 12], [7, 12], [8, 12], [9, 12], [10, 12], [11, 12], [12, 12], [13, 12], [14, 12], [15, 12], [16, 12], [17, 12], [18, 12]],
  highGround: [[3, 0], [15, 0], [3, 1], [4, 1], [5, 1], [13, 1], [14, 1], [15, 1], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [11, 2], [12, 2], [13, 2], [4, 3], [5, 3], [12, 3], [13, 3], [4, 4], [5, 4], [12, 4], [13, 4], [4, 5], [5, 5], [2, 6], [2, 7], [3, 7], [3, 8], [4, 8], [5, 8], [6, 8], [7, 8], [8, 8], [9, 8], [10, 8], [11, 8], [12, 8], [13, 8], [14, 8], [4, 9], [5, 9], [6, 9], [7, 9], [8, 9], [9, 9], [10, 9], [11, 9], [12, 9], [13, 9], [14, 9], [5, 10], [6, 10], [13, 10], [14, 10], [15, 10], [16, 10], [5, 11], [6, 11], [5, 12]],
  collisionWalls: [
    { tx: 2, ty: 0, edge: "E" as const },
    { tx: 3, ty: 0, edge: "E" as const },
    { tx: 3, ty: 0, edge: "N" as const },
    { tx: 4, ty: 0, edge: "N" as const },
    { tx: 4, ty: 0, edge: "S" as const },
    { tx: 5, ty: 0, edge: "S" as const },
    { tx: 13, ty: 0, edge: "S" as const },
    { tx: 14, ty: 0, edge: "E" as const },
    { tx: 14, ty: 0, edge: "N" as const },
    { tx: 14, ty: 0, edge: "S" as const },
    { tx: 15, ty: 0, edge: "E" as const },
    { tx: 2, ty: 1, edge: "E" as const },
    { tx: 5, ty: 1, edge: "E" as const },
    { tx: 6, ty: 1, edge: "S" as const },
    { tx: 7, ty: 1, edge: "S" as const },
    { tx: 11, ty: 1, edge: "S" as const },
    { tx: 12, ty: 1, edge: "E" as const },
    { tx: 12, ty: 1, edge: "S" as const },
    { tx: 14, ty: 1, edge: "S" as const },
    { tx: 15, ty: 1, edge: "S" as const },
    { tx: 1, ty: 2, edge: "E" as const },
    { tx: 2, ty: 2, edge: "S" as const },
    { tx: 3, ty: 2, edge: "S" as const },
    { tx: 7, ty: 2, edge: "E" as const },
    { tx: 7, ty: 2, edge: "S" as const },
    { tx: 8, ty: 2, edge: "S" as const },
    { tx: 9, ty: 2, edge: "S" as const },
    { tx: 10, ty: 2, edge: "E" as const },
    { tx: 10, ty: 2, edge: "S" as const },
    { tx: 13, ty: 2, edge: "E" as const },
    { tx: 3, ty: 3, edge: "E" as const },
    { tx: 5, ty: 3, edge: "E" as const },
    { tx: 11, ty: 3, edge: "E" as const },
    { tx: 13, ty: 3, edge: "E" as const },
    { tx: 3, ty: 4, edge: "E" as const },
    { tx: 5, ty: 4, edge: "E" as const },
    { tx: 11, ty: 4, edge: "E" as const },
    { tx: 12, ty: 4, edge: "S" as const },
    { tx: 13, ty: 4, edge: "E" as const },
    { tx: 2, ty: 5, edge: "S" as const },
    { tx: 3, ty: 5, edge: "E" as const },
    { tx: 4, ty: 5, edge: "S" as const },
    { tx: 5, ty: 5, edge: "E" as const },
    { tx: 5, ty: 5, edge: "S" as const },
    { tx: 1, ty: 6, edge: "E" as const },
    { tx: 2, ty: 6, edge: "E" as const },
    { tx: 3, ty: 6, edge: "S" as const },
    { tx: 1, ty: 7, edge: "E" as const },
    { tx: 2, ty: 7, edge: "S" as const },
    { tx: 3, ty: 7, edge: "E" as const },
    { tx: 4, ty: 7, edge: "S" as const },
    { tx: 5, ty: 7, edge: "S" as const },
    { tx: 6, ty: 7, edge: "S" as const },
    { tx: 7, ty: 7, edge: "S" as const },
    { tx: 8, ty: 7, edge: "S" as const },
    { tx: 10, ty: 7, edge: "S" as const },
    { tx: 11, ty: 7, edge: "S" as const },
    { tx: 12, ty: 7, edge: "S" as const },
    { tx: 14, ty: 7, edge: "S" as const },
    { tx: 2, ty: 8, edge: "E" as const },
    { tx: 3, ty: 8, edge: "S" as const },
    { tx: 14, ty: 8, edge: "E" as const },
    { tx: 3, ty: 9, edge: "E" as const },
    { tx: 4, ty: 9, edge: "S" as const },
    { tx: 7, ty: 9, edge: "S" as const },
    { tx: 8, ty: 9, edge: "S" as const },
    { tx: 9, ty: 9, edge: "S" as const },
    { tx: 10, ty: 9, edge: "S" as const },
    { tx: 11, ty: 9, edge: "S" as const },
    { tx: 12, ty: 9, edge: "S" as const },
    { tx: 14, ty: 9, edge: "E" as const },
    { tx: 15, ty: 9, edge: "S" as const },
    { tx: 4, ty: 10, edge: "E" as const },
    { tx: 6, ty: 10, edge: "E" as const },
    { tx: 12, ty: 10, edge: "E" as const },
    { tx: 13, ty: 10, edge: "S" as const },
    { tx: 14, ty: 10, edge: "S" as const },
    { tx: 15, ty: 10, edge: "S" as const },
    { tx: 16, ty: 10, edge: "E" as const },
    { tx: 16, ty: 10, edge: "S" as const },
    { tx: 17, ty: 10, edge: "S" as const },
    { tx: 6, ty: 11, edge: "E" as const },
    { tx: 6, ty: 11, edge: "S" as const },
    { tx: 17, ty: 11, edge: "E" as const },
    { tx: 18, ty: 11, edge: "S" as const },
    { tx: 4, ty: 12, edge: "E" as const },
    { tx: 5, ty: 12, edge: "E" as const },
    { tx: 5, ty: 12, edge: "S" as const },
    { tx: 6, ty: 12, edge: "S" as const },
    { tx: 18, ty: 12, edge: "E" as const },
    { tx: 18, ty: 12, edge: "S" as const },
  ],
  bridges: [
    { tx: 13, ty: 5, orientation: "V" as const },
    { tx: 13, ty: 6, orientation: "V" as const },
    { tx: 13, ty: 7, orientation: "V" as const },
  ],
  zones: [
    {
      type: "RESOURCE_SITE",
      name: "RESOURCE SITE",
      cells: [[18, 7], [18, 8], [19, 8], [19, 9], [19, 10], [19, 11]],
    },
  ],
};
